### ISSUE TITLE
Binding : 백그라운드뷰와 뷰모델 바인딩

### ISSUE THREAD

**Issue by iammiori** [miori-app/CrossfitJangBiBBal#23]
##  Description
- 백그라운드뷰와 뷰모델 바인딩
## To-do
- [x] 테이블뷰 뷰모델에서 백그라운드뷰 뷰모델 받아와, fetch 시점에 백그라운드뷰 뷰모델  값 변경 
- [x] 테이블 뷰에서 바인딩 함수구현
- [x] 뷰컨트롤러에서 바인딩 함수 호출
